package de.hska.wi.awp.datasource.infosys.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Allgemeines service. Represents a row in the &quot;datasourceInfosys_Allgemeines&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.hska.wi.awp.datasource.infosys.model.impl.AllgemeinesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.hska.wi.awp.datasource.infosys.model.impl.AllgemeinesImpl}.
 * </p>
 *
 * @author Daniel Storch
 * @see Allgemeines
 * @see de.hska.wi.awp.datasource.infosys.model.impl.AllgemeinesImpl
 * @see de.hska.wi.awp.datasource.infosys.model.impl.AllgemeinesModelImpl
 * @generated
 */
public interface AllgemeinesModel extends BaseModel<Allgemeines> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a allgemeines model instance should use the {@link Allgemeines} interface instead.
     */

    /**
     * Returns the primary key of this allgemeines.
     *
     * @return the primary key of this allgemeines
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this allgemeines.
     *
     * @param primaryKey the primary key of this allgemeines
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this allgemeines.
     *
     * @return the ID of this allgemeines
     */
    public long getId();

    /**
     * Sets the ID of this allgemeines.
     *
     * @param id the ID of this allgemeines
     */
    public void setId(long id);

    /**
     * Returns the statusbricht_id of this allgemeines.
     *
     * @return the statusbricht_id of this allgemeines
     */
    public long getStatusbricht_id();

    /**
     * Sets the statusbricht_id of this allgemeines.
     *
     * @param statusbricht_id the statusbricht_id of this allgemeines
     */
    public void setStatusbricht_id(long statusbricht_id);

    /**
     * Returns the probleme_risiken of this allgemeines.
     *
     * @return the probleme_risiken of this allgemeines
     */
    @AutoEscape
    public String getProbleme_risiken();

    /**
     * Sets the probleme_risiken of this allgemeines.
     *
     * @param probleme_risiken the probleme_risiken of this allgemeines
     */
    public void setProbleme_risiken(String probleme_risiken);

    /**
     * Returns the massnahmen of this allgemeines.
     *
     * @return the massnahmen of this allgemeines
     */
    @AutoEscape
    public String getMassnahmen();

    /**
     * Sets the massnahmen of this allgemeines.
     *
     * @param massnahmen the massnahmen of this allgemeines
     */
    public void setMassnahmen(String massnahmen);

    /**
     * Returns the situation of this allgemeines.
     *
     * @return the situation of this allgemeines
     */
    @AutoEscape
    public String getSituation();

    /**
     * Sets the situation of this allgemeines.
     *
     * @param situation the situation of this allgemeines
     */
    public void setSituation(String situation);

    /**
     * Returns the gruende of this allgemeines.
     *
     * @return the gruende of this allgemeines
     */
    @AutoEscape
    public String getGruende();

    /**
     * Sets the gruende of this allgemeines.
     *
     * @param gruende the gruende of this allgemeines
     */
    public void setGruende(String gruende);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        de.hska.wi.awp.datasource.infosys.model.Allgemeines allgemeines);

    @Override
    public int hashCode();

    @Override
    public CacheModel<de.hska.wi.awp.datasource.infosys.model.Allgemeines> toCacheModel();

    @Override
    public de.hska.wi.awp.datasource.infosys.model.Allgemeines toEscapedModel();

    @Override
    public de.hska.wi.awp.datasource.infosys.model.Allgemeines toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
