package de.hska.wi.awp.datasource.infosys.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Feedback service. Represents a row in the &quot;datasourceInfosys_Feedback&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.hska.wi.awp.datasource.infosys.model.impl.FeedbackModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.hska.wi.awp.datasource.infosys.model.impl.FeedbackImpl}.
 * </p>
 *
 * @author Daniel Storch
 * @see Feedback
 * @see de.hska.wi.awp.datasource.infosys.model.impl.FeedbackImpl
 * @see de.hska.wi.awp.datasource.infosys.model.impl.FeedbackModelImpl
 * @generated
 */
public interface FeedbackModel extends BaseModel<Feedback> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a feedback model instance should use the {@link Feedback} interface instead.
     */

    /**
     * Returns the primary key of this feedback.
     *
     * @return the primary key of this feedback
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this feedback.
     *
     * @param primaryKey the primary key of this feedback
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this feedback.
     *
     * @return the ID of this feedback
     */
    public long getId();

    /**
     * Sets the ID of this feedback.
     *
     * @param id the ID of this feedback
     */
    public void setId(long id);

    /**
     * Returns the student_id of this feedback.
     *
     * @return the student_id of this feedback
     */
    public long getStudent_id();

    /**
     * Sets the student_id of this feedback.
     *
     * @param student_id the student_id of this feedback
     */
    public void setStudent_id(long student_id);

    /**
     * Returns the feedback_runden_nr of this feedback.
     *
     * @return the feedback_runden_nr of this feedback
     */
    public int getFeedback_runden_nr();

    /**
     * Sets the feedback_runden_nr of this feedback.
     *
     * @param feedback_runden_nr the feedback_runden_nr of this feedback
     */
    public void setFeedback_runden_nr(int feedback_runden_nr);

    /**
     * Returns the eigenbewertung of this feedback.
     *
     * @return the eigenbewertung of this feedback
     */
    @AutoEscape
    public String getEigenbewertung();

    /**
     * Sets the eigenbewertung of this feedback.
     *
     * @param eigenbewertung the eigenbewertung of this feedback
     */
    public void setEigenbewertung(String eigenbewertung);

    /**
     * Returns the kommentar_kompetenzen of this feedback.
     *
     * @return the kommentar_kompetenzen of this feedback
     */
    @AutoEscape
    public String getKommentar_kompetenzen();

    /**
     * Sets the kommentar_kompetenzen of this feedback.
     *
     * @param kommentar_kompetenzen the kommentar_kompetenzen of this feedback
     */
    public void setKommentar_kompetenzen(String kommentar_kompetenzen);

    /**
     * Returns the kommentar_beitrag of this feedback.
     *
     * @return the kommentar_beitrag of this feedback
     */
    @AutoEscape
    public String getKommentar_beitrag();

    /**
     * Sets the kommentar_beitrag of this feedback.
     *
     * @param kommentar_beitrag the kommentar_beitrag of this feedback
     */
    public void setKommentar_beitrag(String kommentar_beitrag);

    /**
     * Returns the beitrag of this feedback.
     *
     * @return the beitrag of this feedback
     */
    public int getBeitrag();

    /**
     * Sets the beitrag of this feedback.
     *
     * @param beitrag the beitrag of this feedback
     */
    public void setBeitrag(int beitrag);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        de.hska.wi.awp.datasource.infosys.model.Feedback feedback);

    @Override
    public int hashCode();

    @Override
    public CacheModel<de.hska.wi.awp.datasource.infosys.model.Feedback> toCacheModel();

    @Override
    public de.hska.wi.awp.datasource.infosys.model.Feedback toEscapedModel();

    @Override
    public de.hska.wi.awp.datasource.infosys.model.Feedback toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
