package de.hska.wi.awp.datasource.infosys.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Geplante_arbeit service. Represents a row in the &quot;datasourceInfosys_Geplante_arbeit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.hska.wi.awp.datasource.infosys.model.impl.Geplante_arbeitModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.hska.wi.awp.datasource.infosys.model.impl.Geplante_arbeitImpl}.
 * </p>
 *
 * @author Daniel Storch
 * @see Geplante_arbeit
 * @see de.hska.wi.awp.datasource.infosys.model.impl.Geplante_arbeitImpl
 * @see de.hska.wi.awp.datasource.infosys.model.impl.Geplante_arbeitModelImpl
 * @generated
 */
public interface Geplante_arbeitModel extends BaseModel<Geplante_arbeit> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a geplante_arbeit model instance should use the {@link Geplante_arbeit} interface instead.
     */

    /**
     * Returns the primary key of this geplante_arbeit.
     *
     * @return the primary key of this geplante_arbeit
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this geplante_arbeit.
     *
     * @param primaryKey the primary key of this geplante_arbeit
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this geplante_arbeit.
     *
     * @return the ID of this geplante_arbeit
     */
    public long getId();

    /**
     * Sets the ID of this geplante_arbeit.
     *
     * @param id the ID of this geplante_arbeit
     */
    public void setId(long id);

    /**
     * Returns the statusbericht_id of this geplante_arbeit.
     *
     * @return the statusbericht_id of this geplante_arbeit
     */
    public long getStatusbericht_id();

    /**
     * Sets the statusbericht_id of this geplante_arbeit.
     *
     * @param statusbericht_id the statusbericht_id of this geplante_arbeit
     */
    public void setStatusbericht_id(long statusbericht_id);

    /**
     * Returns the verantwortlicher of this geplante_arbeit.
     *
     * @return the verantwortlicher of this geplante_arbeit
     */
    public long getVerantwortlicher();

    /**
     * Sets the verantwortlicher of this geplante_arbeit.
     *
     * @param verantwortlicher the verantwortlicher of this geplante_arbeit
     */
    public void setVerantwortlicher(long verantwortlicher);

    /**
     * Returns the arbeit of this geplante_arbeit.
     *
     * @return the arbeit of this geplante_arbeit
     */
    @AutoEscape
    public String getArbeit();

    /**
     * Sets the arbeit of this geplante_arbeit.
     *
     * @param arbeit the arbeit of this geplante_arbeit
     */
    public void setArbeit(String arbeit);

    /**
     * Returns the bis_wann of this geplante_arbeit.
     *
     * @return the bis_wann of this geplante_arbeit
     */
    public Date getBis_wann();

    /**
     * Sets the bis_wann of this geplante_arbeit.
     *
     * @param bis_wann the bis_wann of this geplante_arbeit
     */
    public void setBis_wann(Date bis_wann);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        de.hska.wi.awp.datasource.infosys.model.Geplante_arbeit geplante_arbeit);

    @Override
    public int hashCode();

    @Override
    public CacheModel<de.hska.wi.awp.datasource.infosys.model.Geplante_arbeit> toCacheModel();

    @Override
    public de.hska.wi.awp.datasource.infosys.model.Geplante_arbeit toEscapedModel();

    @Override
    public de.hska.wi.awp.datasource.infosys.model.Geplante_arbeit toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
