package de.hska.wi.awp.datasource.infosys.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Rolle service. Represents a row in the &quot;datasourceInfosys_Rolle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.hska.wi.awp.datasource.infosys.model.impl.RolleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.hska.wi.awp.datasource.infosys.model.impl.RolleImpl}.
 * </p>
 *
 * @author Daniel Storch
 * @see Rolle
 * @see de.hska.wi.awp.datasource.infosys.model.impl.RolleImpl
 * @see de.hska.wi.awp.datasource.infosys.model.impl.RolleModelImpl
 * @generated
 */
public interface RolleModel extends BaseModel<Rolle> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a rolle model instance should use the {@link Rolle} interface instead.
     */

    /**
     * Returns the primary key of this rolle.
     *
     * @return the primary key of this rolle
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this rolle.
     *
     * @param primaryKey the primary key of this rolle
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this rolle.
     *
     * @return the ID of this rolle
     */
    public long getId();

    /**
     * Sets the ID of this rolle.
     *
     * @param id the ID of this rolle
     */
    public void setId(long id);

    /**
     * Returns the short name of this rolle.
     *
     * @return the short name of this rolle
     */
    @AutoEscape
    public String getShortName();

    /**
     * Sets the short name of this rolle.
     *
     * @param shortName the short name of this rolle
     */
    public void setShortName(String shortName);

    /**
     * Returns the name of this rolle.
     *
     * @return the name of this rolle
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this rolle.
     *
     * @param name the name of this rolle
     */
    public void setName(String name);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(de.hska.wi.awp.datasource.infosys.model.Rolle rolle);

    @Override
    public int hashCode();

    @Override
    public CacheModel<de.hska.wi.awp.datasource.infosys.model.Rolle> toCacheModel();

    @Override
    public de.hska.wi.awp.datasource.infosys.model.Rolle toEscapedModel();

    @Override
    public de.hska.wi.awp.datasource.infosys.model.Rolle toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
