package de.hska.wi.awp.datasource.infosys.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Statusueberblick service. Represents a row in the &quot;datasourceInfosys_Statusueberblick&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.hska.wi.awp.datasource.infosys.model.impl.StatusueberblickModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.hska.wi.awp.datasource.infosys.model.impl.StatusueberblickImpl}.
 * </p>
 *
 * @author Daniel Storch
 * @see Statusueberblick
 * @see de.hska.wi.awp.datasource.infosys.model.impl.StatusueberblickImpl
 * @see de.hska.wi.awp.datasource.infosys.model.impl.StatusueberblickModelImpl
 * @generated
 */
public interface StatusueberblickModel extends BaseModel<Statusueberblick> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a statusueberblick model instance should use the {@link Statusueberblick} interface instead.
     */

    /**
     * Returns the primary key of this statusueberblick.
     *
     * @return the primary key of this statusueberblick
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this statusueberblick.
     *
     * @param primaryKey the primary key of this statusueberblick
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this statusueberblick.
     *
     * @return the ID of this statusueberblick
     */
    public long getId();

    /**
     * Sets the ID of this statusueberblick.
     *
     * @param id the ID of this statusueberblick
     */
    public void setId(long id);

    /**
     * Returns the statusbericht_id of this statusueberblick.
     *
     * @return the statusbericht_id of this statusueberblick
     */
    public long getStatusbericht_id();

    /**
     * Sets the statusbericht_id of this statusueberblick.
     *
     * @param statusbericht_id the statusbericht_id of this statusueberblick
     */
    public void setStatusbericht_id(long statusbericht_id);

    /**
     * Returns the qualitaet_status of this statusueberblick.
     *
     * @return the qualitaet_status of this statusueberblick
     */
    @AutoEscape
    public String getQualitaet_status();

    /**
     * Sets the qualitaet_status of this statusueberblick.
     *
     * @param qualitaet_status the qualitaet_status of this statusueberblick
     */
    public void setQualitaet_status(String qualitaet_status);

    /**
     * Returns the qualitaet_text of this statusueberblick.
     *
     * @return the qualitaet_text of this statusueberblick
     */
    @AutoEscape
    public String getQualitaet_text();

    /**
     * Sets the qualitaet_text of this statusueberblick.
     *
     * @param qualitaet_text the qualitaet_text of this statusueberblick
     */
    public void setQualitaet_text(String qualitaet_text);

    /**
     * Returns the kosten_text of this statusueberblick.
     *
     * @return the kosten_text of this statusueberblick
     */
    @AutoEscape
    public String getKosten_text();

    /**
     * Sets the kosten_text of this statusueberblick.
     *
     * @param kosten_text the kosten_text of this statusueberblick
     */
    public void setKosten_text(String kosten_text);

    /**
     * Returns the kosten_status of this statusueberblick.
     *
     * @return the kosten_status of this statusueberblick
     */
    @AutoEscape
    public String getKosten_status();

    /**
     * Sets the kosten_status of this statusueberblick.
     *
     * @param kosten_status the kosten_status of this statusueberblick
     */
    public void setKosten_status(String kosten_status);

    /**
     * Returns the aufwand_status of this statusueberblick.
     *
     * @return the aufwand_status of this statusueberblick
     */
    @AutoEscape
    public String getAufwand_status();

    /**
     * Sets the aufwand_status of this statusueberblick.
     *
     * @param aufwand_status the aufwand_status of this statusueberblick
     */
    public void setAufwand_status(String aufwand_status);

    /**
     * Returns the aufwand_text of this statusueberblick.
     *
     * @return the aufwand_text of this statusueberblick
     */
    @AutoEscape
    public String getAufwand_text();

    /**
     * Sets the aufwand_text of this statusueberblick.
     *
     * @param aufwand_text the aufwand_text of this statusueberblick
     */
    public void setAufwand_text(String aufwand_text);

    /**
     * Returns the termine_status of this statusueberblick.
     *
     * @return the termine_status of this statusueberblick
     */
    @AutoEscape
    public String getTermine_status();

    /**
     * Sets the termine_status of this statusueberblick.
     *
     * @param termine_status the termine_status of this statusueberblick
     */
    public void setTermine_status(String termine_status);

    /**
     * Returns the termine_text of this statusueberblick.
     *
     * @return the termine_text of this statusueberblick
     */
    @AutoEscape
    public String getTermine_text();

    /**
     * Sets the termine_text of this statusueberblick.
     *
     * @param termine_text the termine_text of this statusueberblick
     */
    public void setTermine_text(String termine_text);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        de.hska.wi.awp.datasource.infosys.model.Statusueberblick statusueberblick);

    @Override
    public int hashCode();

    @Override
    public CacheModel<de.hska.wi.awp.datasource.infosys.model.Statusueberblick> toCacheModel();

    @Override
    public de.hska.wi.awp.datasource.infosys.model.Statusueberblick toEscapedModel();

    @Override
    public de.hska.wi.awp.datasource.infosys.model.Statusueberblick toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
