package de.hska.wi.awp.datasource.infosys.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import de.hska.wi.awp.datasource.infosys.model.Allgemeines;
import de.hska.wi.awp.datasource.infosys.service.AllgemeinesLocalServiceUtil;

/**
 * The extended model base implementation for the Allgemeines service. Represents a row in the &quot;datasourceInfosys_Allgemeines&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AllgemeinesImpl}.
 * </p>
 *
 * @author Daniel Storch
 * @see AllgemeinesImpl
 * @see de.hska.wi.awp.datasource.infosys.model.Allgemeines
 * @generated
 */
public abstract class AllgemeinesBaseImpl extends AllgemeinesModelImpl
    implements Allgemeines {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a allgemeines model instance should use the {@link Allgemeines} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            AllgemeinesLocalServiceUtil.addAllgemeines(this);
        } else {
            AllgemeinesLocalServiceUtil.updateAllgemeines(this);
        }
    }
}
