package de.hska.wi.awp.datasource.infosys.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import de.hska.wi.awp.datasource.infosys.model.Bewertungskriterium;
import de.hska.wi.awp.datasource.infosys.model.BewertungskriteriumModel;
import de.hska.wi.awp.datasource.infosys.model.BewertungskriteriumSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Bewertungskriterium service. Represents a row in the &quot;datasourceInfosys_Bewertungskriterium&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link de.hska.wi.awp.datasource.infosys.model.BewertungskriteriumModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BewertungskriteriumImpl}.
 * </p>
 *
 * @author Daniel Storch
 * @see BewertungskriteriumImpl
 * @see de.hska.wi.awp.datasource.infosys.model.Bewertungskriterium
 * @see de.hska.wi.awp.datasource.infosys.model.BewertungskriteriumModel
 * @generated
 */
@JSON(strict = true)
public class BewertungskriteriumModelImpl extends BaseModelImpl<Bewertungskriterium>
    implements BewertungskriteriumModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a bewertungskriterium model instance should use the {@link de.hska.wi.awp.datasource.infosys.model.Bewertungskriterium} interface instead.
     */
    public static final String TABLE_NAME = "datasourceInfosys_Bewertungskriterium";
    public static final Object[][] TABLE_COLUMNS = {
            { "id_", Types.BIGINT },
            { "name", Types.VARCHAR },
            { "beschreibung", Types.VARCHAR },
            { "gewichtung", Types.INTEGER }
        };
    public static final String TABLE_SQL_CREATE = "create table datasourceInfosys_Bewertungskriterium (id_ LONG not null primary key,name VARCHAR(75) null,beschreibung VARCHAR(75) null,gewichtung INTEGER)";
    public static final String TABLE_SQL_DROP = "drop table datasourceInfosys_Bewertungskriterium";
    public static final String ORDER_BY_JPQL = " ORDER BY bewertungskriterium.id ASC";
    public static final String ORDER_BY_SQL = " ORDER BY datasourceInfosys_Bewertungskriterium.id_ ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.de.hska.wi.awp.datasource.infosys.model.Bewertungskriterium"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.de.hska.wi.awp.datasource.infosys.model.Bewertungskriterium"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.de.hska.wi.awp.datasource.infosys.model.Bewertungskriterium"));
    private static ClassLoader _classLoader = Bewertungskriterium.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Bewertungskriterium.class
        };
    private long _id;
    private String _name;
    private String _beschreibung;
    private int _gewichtung;
    private Bewertungskriterium _escapedModel;

    public BewertungskriteriumModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Bewertungskriterium toModel(BewertungskriteriumSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Bewertungskriterium model = new BewertungskriteriumImpl();

        model.setId(soapModel.getId());
        model.setName(soapModel.getName());
        model.setBeschreibung(soapModel.getBeschreibung());
        model.setGewichtung(soapModel.getGewichtung());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Bewertungskriterium> toModels(
        BewertungskriteriumSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Bewertungskriterium> models = new ArrayList<Bewertungskriterium>(soapModels.length);

        for (BewertungskriteriumSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _id;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _id;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Bewertungskriterium.class;
    }

    @Override
    public String getModelClassName() {
        return Bewertungskriterium.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("id", getId());
        attributes.put("name", getName());
        attributes.put("beschreibung", getBeschreibung());
        attributes.put("gewichtung", getGewichtung());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long id = (Long) attributes.get("id");

        if (id != null) {
            setId(id);
        }

        String name = (String) attributes.get("name");

        if (name != null) {
            setName(name);
        }

        String beschreibung = (String) attributes.get("beschreibung");

        if (beschreibung != null) {
            setBeschreibung(beschreibung);
        }

        Integer gewichtung = (Integer) attributes.get("gewichtung");

        if (gewichtung != null) {
            setGewichtung(gewichtung);
        }
    }

    @JSON
    @Override
    public long getId() {
        return _id;
    }

    @Override
    public void setId(long id) {
        _id = id;
    }

    @JSON
    @Override
    public String getName() {
        if (_name == null) {
            return StringPool.BLANK;
        } else {
            return _name;
        }
    }

    @Override
    public void setName(String name) {
        _name = name;
    }

    @JSON
    @Override
    public String getBeschreibung() {
        if (_beschreibung == null) {
            return StringPool.BLANK;
        } else {
            return _beschreibung;
        }
    }

    @Override
    public void setBeschreibung(String beschreibung) {
        _beschreibung = beschreibung;
    }

    @JSON
    @Override
    public int getGewichtung() {
        return _gewichtung;
    }

    @Override
    public void setGewichtung(int gewichtung) {
        _gewichtung = gewichtung;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            Bewertungskriterium.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Bewertungskriterium toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Bewertungskriterium) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        BewertungskriteriumImpl bewertungskriteriumImpl = new BewertungskriteriumImpl();

        bewertungskriteriumImpl.setId(getId());
        bewertungskriteriumImpl.setName(getName());
        bewertungskriteriumImpl.setBeschreibung(getBeschreibung());
        bewertungskriteriumImpl.setGewichtung(getGewichtung());

        bewertungskriteriumImpl.resetOriginalValues();

        return bewertungskriteriumImpl;
    }

    @Override
    public int compareTo(Bewertungskriterium bewertungskriterium) {
        long primaryKey = bewertungskriterium.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Bewertungskriterium)) {
            return false;
        }

        Bewertungskriterium bewertungskriterium = (Bewertungskriterium) obj;

        long primaryKey = bewertungskriterium.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<Bewertungskriterium> toCacheModel() {
        BewertungskriteriumCacheModel bewertungskriteriumCacheModel = new BewertungskriteriumCacheModel();

        bewertungskriteriumCacheModel.id = getId();

        bewertungskriteriumCacheModel.name = getName();

        String name = bewertungskriteriumCacheModel.name;

        if ((name != null) && (name.length() == 0)) {
            bewertungskriteriumCacheModel.name = null;
        }

        bewertungskriteriumCacheModel.beschreibung = getBeschreibung();

        String beschreibung = bewertungskriteriumCacheModel.beschreibung;

        if ((beschreibung != null) && (beschreibung.length() == 0)) {
            bewertungskriteriumCacheModel.beschreibung = null;
        }

        bewertungskriteriumCacheModel.gewichtung = getGewichtung();

        return bewertungskriteriumCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(9);

        sb.append("{id=");
        sb.append(getId());
        sb.append(", name=");
        sb.append(getName());
        sb.append(", beschreibung=");
        sb.append(getBeschreibung());
        sb.append(", gewichtung=");
        sb.append(getGewichtung());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(16);

        sb.append("<model><model-name>");
        sb.append("de.hska.wi.awp.datasource.infosys.model.Bewertungskriterium");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>id</column-name><column-value><![CDATA[");
        sb.append(getId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>name</column-name><column-value><![CDATA[");
        sb.append(getName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>beschreibung</column-name><column-value><![CDATA[");
        sb.append(getBeschreibung());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>gewichtung</column-name><column-value><![CDATA[");
        sb.append(getGewichtung());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
