package de.hska.wi.awp.datasource.infosys.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import de.hska.wi.awp.datasource.infosys.model.Bewertungskriterium;
import de.hska.wi.awp.datasource.infosys.service.BewertungskriteriumLocalServiceUtil;

/**
 * The extended model base implementation for the Bewertungskriterium service. Represents a row in the &quot;datasourceInfosys_Bewertungskriterium&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BewertungskriteriumImpl}.
 * </p>
 *
 * @author Daniel Storch
 * @see BewertungskriteriumImpl
 * @see de.hska.wi.awp.datasource.infosys.model.Bewertungskriterium
 * @generated
 */
public abstract class BewertungskriteriumBaseImpl
    extends BewertungskriteriumModelImpl implements Bewertungskriterium {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a bewertungskriterium model instance should use the {@link Bewertungskriterium} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            BewertungskriteriumLocalServiceUtil.addBewertungskriterium(this);
        } else {
            BewertungskriteriumLocalServiceUtil.updateBewertungskriterium(this);
        }
    }
}
