package de.hska.wi.awp.datasource.infosys.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import de.hska.wi.awp.datasource.infosys.model.Feedback;
import de.hska.wi.awp.datasource.infosys.service.FeedbackLocalServiceUtil;

/**
 * The extended model base implementation for the Feedback service. Represents a row in the &quot;datasourceInfosys_Feedback&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FeedbackImpl}.
 * </p>
 *
 * @author Daniel Storch
 * @see FeedbackImpl
 * @see de.hska.wi.awp.datasource.infosys.model.Feedback
 * @generated
 */
public abstract class FeedbackBaseImpl extends FeedbackModelImpl
    implements Feedback {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a feedback model instance should use the {@link Feedback} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            FeedbackLocalServiceUtil.addFeedback(this);
        } else {
            FeedbackLocalServiceUtil.updateFeedback(this);
        }
    }
}
