package de.hska.wi.awp.datasource.infosys.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import de.hska.wi.awp.datasource.infosys.model.Geplante_arbeit;
import de.hska.wi.awp.datasource.infosys.service.Geplante_arbeitLocalServiceUtil;

/**
 * The extended model base implementation for the Geplante_arbeit service. Represents a row in the &quot;datasourceInfosys_Geplante_arbeit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Geplante_arbeitImpl}.
 * </p>
 *
 * @author Daniel Storch
 * @see Geplante_arbeitImpl
 * @see de.hska.wi.awp.datasource.infosys.model.Geplante_arbeit
 * @generated
 */
public abstract class Geplante_arbeitBaseImpl extends Geplante_arbeitModelImpl
    implements Geplante_arbeit {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a geplante_arbeit model instance should use the {@link Geplante_arbeit} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            Geplante_arbeitLocalServiceUtil.addGeplante_arbeit(this);
        } else {
            Geplante_arbeitLocalServiceUtil.updateGeplante_arbeit(this);
        }
    }
}
