package de.hska.wi.awp.datasource.infosys.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import de.hska.wi.awp.datasource.infosys.model.Rolle;
import de.hska.wi.awp.datasource.infosys.service.RolleLocalServiceUtil;

/**
 * The extended model base implementation for the Rolle service. Represents a row in the &quot;datasourceInfosys_Rolle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RolleImpl}.
 * </p>
 *
 * @author Daniel Storch
 * @see RolleImpl
 * @see de.hska.wi.awp.datasource.infosys.model.Rolle
 * @generated
 */
public abstract class RolleBaseImpl extends RolleModelImpl implements Rolle {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a rolle model instance should use the {@link Rolle} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            RolleLocalServiceUtil.addRolle(this);
        } else {
            RolleLocalServiceUtil.updateRolle(this);
        }
    }
}
