package de.hska.wi.awp.datasource.infosys.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import de.hska.wi.awp.datasource.infosys.model.Statusueberblick;
import de.hska.wi.awp.datasource.infosys.service.StatusueberblickLocalServiceUtil;

/**
 * The extended model base implementation for the Statusueberblick service. Represents a row in the &quot;datasourceInfosys_Statusueberblick&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StatusueberblickImpl}.
 * </p>
 *
 * @author Daniel Storch
 * @see StatusueberblickImpl
 * @see de.hska.wi.awp.datasource.infosys.model.Statusueberblick
 * @generated
 */
public abstract class StatusueberblickBaseImpl extends StatusueberblickModelImpl
    implements Statusueberblick {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a statusueberblick model instance should use the {@link Statusueberblick} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            StatusueberblickLocalServiceUtil.addStatusueberblick(this);
        } else {
            StatusueberblickLocalServiceUtil.updateStatusueberblick(this);
        }
    }
}
