package de.hska.wi.awp.datasource.infosys.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import de.hska.wi.awp.datasource.infosys.model.Statusbericht_info;
import de.hska.wi.awp.datasource.infosys.service.Statusbericht_infoLocalServiceUtil;

/**
 * The extended model base implementation for the Statusbericht_info service. Represents a row in the &quot;datasourceInfosys_Statusbericht_info&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Statusbericht_infoImpl}.
 * </p>
 *
 * @author Daniel Storch
 * @see Statusbericht_infoImpl
 * @see de.hska.wi.awp.datasource.infosys.model.Statusbericht_info
 * @generated
 */
public abstract class Statusbericht_infoBaseImpl
    extends Statusbericht_infoModelImpl implements Statusbericht_info {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a statusbericht_info model instance should use the {@link Statusbericht_info} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            Statusbericht_infoLocalServiceUtil.addStatusbericht_info(this);
        } else {
            Statusbericht_infoLocalServiceUtil.updateStatusbericht_info(this);
        }
    }
}
