package de.hska.wi.awp.datasource.infosys.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import de.hska.wi.awp.datasource.infosys.model.Statusbericht_detail_punkt;
import de.hska.wi.awp.datasource.infosys.model.Statusbericht_detail_punktModel;
import de.hska.wi.awp.datasource.infosys.model.Statusbericht_detail_punktSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Statusbericht_detail_punkt service. Represents a row in the &quot;datasourceInfosys_Statusbericht_detail_punkt&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link de.hska.wi.awp.datasource.infosys.model.Statusbericht_detail_punktModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Statusbericht_detail_punktImpl}.
 * </p>
 *
 * @author Daniel Storch
 * @see Statusbericht_detail_punktImpl
 * @see de.hska.wi.awp.datasource.infosys.model.Statusbericht_detail_punkt
 * @see de.hska.wi.awp.datasource.infosys.model.Statusbericht_detail_punktModel
 * @generated
 */
@JSON(strict = true)
public class Statusbericht_detail_punktModelImpl extends BaseModelImpl<Statusbericht_detail_punkt>
    implements Statusbericht_detail_punktModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a statusbericht_detail_punkt model instance should use the {@link de.hska.wi.awp.datasource.infosys.model.Statusbericht_detail_punkt} interface instead.
     */
    public static final String TABLE_NAME = "datasourceInfosys_Statusbericht_detail_punkt";
    public static final Object[][] TABLE_COLUMNS = {
            { "id_", Types.BIGINT },
            { "name", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table datasourceInfosys_Statusbericht_detail_punkt (id_ LONG not null primary key,name VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table datasourceInfosys_Statusbericht_detail_punkt";
    public static final String ORDER_BY_JPQL = " ORDER BY statusbericht_detail_punkt.id ASC";
    public static final String ORDER_BY_SQL = " ORDER BY datasourceInfosys_Statusbericht_detail_punkt.id_ ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.de.hska.wi.awp.datasource.infosys.model.Statusbericht_detail_punkt"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.de.hska.wi.awp.datasource.infosys.model.Statusbericht_detail_punkt"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.de.hska.wi.awp.datasource.infosys.model.Statusbericht_detail_punkt"));
    private static ClassLoader _classLoader = Statusbericht_detail_punkt.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Statusbericht_detail_punkt.class
        };
    private long _id;
    private String _name;
    private Statusbericht_detail_punkt _escapedModel;

    public Statusbericht_detail_punktModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Statusbericht_detail_punkt toModel(
        Statusbericht_detail_punktSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Statusbericht_detail_punkt model = new Statusbericht_detail_punktImpl();

        model.setId(soapModel.getId());
        model.setName(soapModel.getName());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Statusbericht_detail_punkt> toModels(
        Statusbericht_detail_punktSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Statusbericht_detail_punkt> models = new ArrayList<Statusbericht_detail_punkt>(soapModels.length);

        for (Statusbericht_detail_punktSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _id;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _id;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Statusbericht_detail_punkt.class;
    }

    @Override
    public String getModelClassName() {
        return Statusbericht_detail_punkt.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("id", getId());
        attributes.put("name", getName());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long id = (Long) attributes.get("id");

        if (id != null) {
            setId(id);
        }

        String name = (String) attributes.get("name");

        if (name != null) {
            setName(name);
        }
    }

    @JSON
    @Override
    public long getId() {
        return _id;
    }

    @Override
    public void setId(long id) {
        _id = id;
    }

    @JSON
    @Override
    public String getName() {
        if (_name == null) {
            return StringPool.BLANK;
        } else {
            return _name;
        }
    }

    @Override
    public void setName(String name) {
        _name = name;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            Statusbericht_detail_punkt.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Statusbericht_detail_punkt toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Statusbericht_detail_punkt) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        Statusbericht_detail_punktImpl statusbericht_detail_punktImpl = new Statusbericht_detail_punktImpl();

        statusbericht_detail_punktImpl.setId(getId());
        statusbericht_detail_punktImpl.setName(getName());

        statusbericht_detail_punktImpl.resetOriginalValues();

        return statusbericht_detail_punktImpl;
    }

    @Override
    public int compareTo(Statusbericht_detail_punkt statusbericht_detail_punkt) {
        long primaryKey = statusbericht_detail_punkt.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Statusbericht_detail_punkt)) {
            return false;
        }

        Statusbericht_detail_punkt statusbericht_detail_punkt = (Statusbericht_detail_punkt) obj;

        long primaryKey = statusbericht_detail_punkt.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<Statusbericht_detail_punkt> toCacheModel() {
        Statusbericht_detail_punktCacheModel statusbericht_detail_punktCacheModel =
            new Statusbericht_detail_punktCacheModel();

        statusbericht_detail_punktCacheModel.id = getId();

        statusbericht_detail_punktCacheModel.name = getName();

        String name = statusbericht_detail_punktCacheModel.name;

        if ((name != null) && (name.length() == 0)) {
            statusbericht_detail_punktCacheModel.name = null;
        }

        return statusbericht_detail_punktCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(5);

        sb.append("{id=");
        sb.append(getId());
        sb.append(", name=");
        sb.append(getName());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(10);

        sb.append("<model><model-name>");
        sb.append(
            "de.hska.wi.awp.datasource.infosys.model.Statusbericht_detail_punkt");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>id</column-name><column-value><![CDATA[");
        sb.append(getId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>name</column-name><column-value><![CDATA[");
        sb.append(getName());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
