package de.hska.wi.awp.datasource.infosys.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import de.hska.wi.awp.datasource.infosys.model.Statusbericht_geplante_arbeit;
import de.hska.wi.awp.datasource.infosys.model.Statusbericht_geplante_arbeitModel;
import de.hska.wi.awp.datasource.infosys.model.Statusbericht_geplante_arbeitSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Statusbericht_geplante_arbeit service. Represents a row in the &quot;datasourceInfosys_Statusbericht_geplante_arbeit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link de.hska.wi.awp.datasource.infosys.model.Statusbericht_geplante_arbeitModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Statusbericht_geplante_arbeitImpl}.
 * </p>
 *
 * @author Daniel Storch
 * @see Statusbericht_geplante_arbeitImpl
 * @see de.hska.wi.awp.datasource.infosys.model.Statusbericht_geplante_arbeit
 * @see de.hska.wi.awp.datasource.infosys.model.Statusbericht_geplante_arbeitModel
 * @generated
 */
@JSON(strict = true)
public class Statusbericht_geplante_arbeitModelImpl extends BaseModelImpl<Statusbericht_geplante_arbeit>
    implements Statusbericht_geplante_arbeitModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a statusbericht_geplante_arbeit model instance should use the {@link de.hska.wi.awp.datasource.infosys.model.Statusbericht_geplante_arbeit} interface instead.
     */
    public static final String TABLE_NAME = "datasourceInfosys_Statusbericht_geplante_arbeit";
    public static final Object[][] TABLE_COLUMNS = {
            { "id_", Types.BIGINT },
            { "aktivitaet", Types.VARCHAR },
            { "bis_wann", Types.TIMESTAMP },
            { "statusbericht_id", Types.BIGINT },
            { "verantwortlicher", Types.BIGINT }
        };
    public static final String TABLE_SQL_CREATE = "create table datasourceInfosys_Statusbericht_geplante_arbeit (id_ LONG not null primary key,aktivitaet VARCHAR(1000) null,bis_wann DATE null,statusbericht_id LONG,verantwortlicher LONG)";
    public static final String TABLE_SQL_DROP = "drop table datasourceInfosys_Statusbericht_geplante_arbeit";
    public static final String ORDER_BY_JPQL = " ORDER BY statusbericht_geplante_arbeit.id ASC";
    public static final String ORDER_BY_SQL = " ORDER BY datasourceInfosys_Statusbericht_geplante_arbeit.id_ ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.de.hska.wi.awp.datasource.infosys.model.Statusbericht_geplante_arbeit"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.de.hska.wi.awp.datasource.infosys.model.Statusbericht_geplante_arbeit"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.de.hska.wi.awp.datasource.infosys.model.Statusbericht_geplante_arbeit"),
            true);
    public static long STATUSBERICHT_ID_COLUMN_BITMASK = 1L;
    public static long ID_COLUMN_BITMASK = 2L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.de.hska.wi.awp.datasource.infosys.model.Statusbericht_geplante_arbeit"));
    private static ClassLoader _classLoader = Statusbericht_geplante_arbeit.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Statusbericht_geplante_arbeit.class
        };
    private long _id;
    private String _aktivitaet;
    private Date _bis_wann;
    private long _statusbericht_id;
    private long _originalStatusbericht_id;
    private boolean _setOriginalStatusbericht_id;
    private long _verantwortlicher;
    private long _columnBitmask;
    private Statusbericht_geplante_arbeit _escapedModel;

    public Statusbericht_geplante_arbeitModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Statusbericht_geplante_arbeit toModel(
        Statusbericht_geplante_arbeitSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Statusbericht_geplante_arbeit model = new Statusbericht_geplante_arbeitImpl();

        model.setId(soapModel.getId());
        model.setAktivitaet(soapModel.getAktivitaet());
        model.setBis_wann(soapModel.getBis_wann());
        model.setStatusbericht_id(soapModel.getStatusbericht_id());
        model.setVerantwortlicher(soapModel.getVerantwortlicher());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Statusbericht_geplante_arbeit> toModels(
        Statusbericht_geplante_arbeitSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Statusbericht_geplante_arbeit> models = new ArrayList<Statusbericht_geplante_arbeit>(soapModels.length);

        for (Statusbericht_geplante_arbeitSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _id;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _id;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Statusbericht_geplante_arbeit.class;
    }

    @Override
    public String getModelClassName() {
        return Statusbericht_geplante_arbeit.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("id", getId());
        attributes.put("aktivitaet", getAktivitaet());
        attributes.put("bis_wann", getBis_wann());
        attributes.put("statusbericht_id", getStatusbericht_id());
        attributes.put("verantwortlicher", getVerantwortlicher());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long id = (Long) attributes.get("id");

        if (id != null) {
            setId(id);
        }

        String aktivitaet = (String) attributes.get("aktivitaet");

        if (aktivitaet != null) {
            setAktivitaet(aktivitaet);
        }

        Date bis_wann = (Date) attributes.get("bis_wann");

        if (bis_wann != null) {
            setBis_wann(bis_wann);
        }

        Long statusbericht_id = (Long) attributes.get("statusbericht_id");

        if (statusbericht_id != null) {
            setStatusbericht_id(statusbericht_id);
        }

        Long verantwortlicher = (Long) attributes.get("verantwortlicher");

        if (verantwortlicher != null) {
            setVerantwortlicher(verantwortlicher);
        }
    }

    @JSON
    @Override
    public long getId() {
        return _id;
    }

    @Override
    public void setId(long id) {
        _id = id;
    }

    @JSON
    @Override
    public String getAktivitaet() {
        if (_aktivitaet == null) {
            return StringPool.BLANK;
        } else {
            return _aktivitaet;
        }
    }

    @Override
    public void setAktivitaet(String aktivitaet) {
        _aktivitaet = aktivitaet;
    }

    @JSON
    @Override
    public Date getBis_wann() {
        return _bis_wann;
    }

    @Override
    public void setBis_wann(Date bis_wann) {
        _bis_wann = bis_wann;
    }

    @JSON
    @Override
    public long getStatusbericht_id() {
        return _statusbericht_id;
    }

    @Override
    public void setStatusbericht_id(long statusbericht_id) {
        _columnBitmask |= STATUSBERICHT_ID_COLUMN_BITMASK;

        if (!_setOriginalStatusbericht_id) {
            _setOriginalStatusbericht_id = true;

            _originalStatusbericht_id = _statusbericht_id;
        }

        _statusbericht_id = statusbericht_id;
    }

    public long getOriginalStatusbericht_id() {
        return _originalStatusbericht_id;
    }

    @JSON
    @Override
    public long getVerantwortlicher() {
        return _verantwortlicher;
    }

    @Override
    public void setVerantwortlicher(long verantwortlicher) {
        _verantwortlicher = verantwortlicher;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            Statusbericht_geplante_arbeit.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Statusbericht_geplante_arbeit toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Statusbericht_geplante_arbeit) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        Statusbericht_geplante_arbeitImpl statusbericht_geplante_arbeitImpl = new Statusbericht_geplante_arbeitImpl();

        statusbericht_geplante_arbeitImpl.setId(getId());
        statusbericht_geplante_arbeitImpl.setAktivitaet(getAktivitaet());
        statusbericht_geplante_arbeitImpl.setBis_wann(getBis_wann());
        statusbericht_geplante_arbeitImpl.setStatusbericht_id(getStatusbericht_id());
        statusbericht_geplante_arbeitImpl.setVerantwortlicher(getVerantwortlicher());

        statusbericht_geplante_arbeitImpl.resetOriginalValues();

        return statusbericht_geplante_arbeitImpl;
    }

    @Override
    public int compareTo(
        Statusbericht_geplante_arbeit statusbericht_geplante_arbeit) {
        long primaryKey = statusbericht_geplante_arbeit.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Statusbericht_geplante_arbeit)) {
            return false;
        }

        Statusbericht_geplante_arbeit statusbericht_geplante_arbeit = (Statusbericht_geplante_arbeit) obj;

        long primaryKey = statusbericht_geplante_arbeit.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        Statusbericht_geplante_arbeitModelImpl statusbericht_geplante_arbeitModelImpl =
            this;

        statusbericht_geplante_arbeitModelImpl._originalStatusbericht_id = statusbericht_geplante_arbeitModelImpl._statusbericht_id;

        statusbericht_geplante_arbeitModelImpl._setOriginalStatusbericht_id = false;

        statusbericht_geplante_arbeitModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Statusbericht_geplante_arbeit> toCacheModel() {
        Statusbericht_geplante_arbeitCacheModel statusbericht_geplante_arbeitCacheModel =
            new Statusbericht_geplante_arbeitCacheModel();

        statusbericht_geplante_arbeitCacheModel.id = getId();

        statusbericht_geplante_arbeitCacheModel.aktivitaet = getAktivitaet();

        String aktivitaet = statusbericht_geplante_arbeitCacheModel.aktivitaet;

        if ((aktivitaet != null) && (aktivitaet.length() == 0)) {
            statusbericht_geplante_arbeitCacheModel.aktivitaet = null;
        }

        Date bis_wann = getBis_wann();

        if (bis_wann != null) {
            statusbericht_geplante_arbeitCacheModel.bis_wann = bis_wann.getTime();
        } else {
            statusbericht_geplante_arbeitCacheModel.bis_wann = Long.MIN_VALUE;
        }

        statusbericht_geplante_arbeitCacheModel.statusbericht_id = getStatusbericht_id();

        statusbericht_geplante_arbeitCacheModel.verantwortlicher = getVerantwortlicher();

        return statusbericht_geplante_arbeitCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(11);

        sb.append("{id=");
        sb.append(getId());
        sb.append(", aktivitaet=");
        sb.append(getAktivitaet());
        sb.append(", bis_wann=");
        sb.append(getBis_wann());
        sb.append(", statusbericht_id=");
        sb.append(getStatusbericht_id());
        sb.append(", verantwortlicher=");
        sb.append(getVerantwortlicher());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(19);

        sb.append("<model><model-name>");
        sb.append(
            "de.hska.wi.awp.datasource.infosys.model.Statusbericht_geplante_arbeit");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>id</column-name><column-value><![CDATA[");
        sb.append(getId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>aktivitaet</column-name><column-value><![CDATA[");
        sb.append(getAktivitaet());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>bis_wann</column-name><column-value><![CDATA[");
        sb.append(getBis_wann());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>statusbericht_id</column-name><column-value><![CDATA[");
        sb.append(getStatusbericht_id());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>verantwortlicher</column-name><column-value><![CDATA[");
        sb.append(getVerantwortlicher());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
