package de.hska.wi.awp.datasource.infosys.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import de.hska.wi.awp.datasource.infosys.model.Statusbericht_detail_punkt;
import de.hska.wi.awp.datasource.infosys.service.Statusbericht_detail_punktLocalServiceUtil;

/**
 * The extended model base implementation for the Statusbericht_detail_punkt service. Represents a row in the &quot;datasourceInfosys_Statusbericht_detail_punkt&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Statusbericht_detail_punktImpl}.
 * </p>
 *
 * @author Daniel Storch
 * @see Statusbericht_detail_punktImpl
 * @see de.hska.wi.awp.datasource.infosys.model.Statusbericht_detail_punkt
 * @generated
 */
public abstract class Statusbericht_detail_punktBaseImpl
    extends Statusbericht_detail_punktModelImpl
    implements Statusbericht_detail_punkt {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a statusbericht_detail_punkt model instance should use the {@link Statusbericht_detail_punkt} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            Statusbericht_detail_punktLocalServiceUtil.addStatusbericht_detail_punkt(this);
        } else {
            Statusbericht_detail_punktLocalServiceUtil.updateStatusbericht_detail_punkt(this);
        }
    }
}
