package de.hska.wi.awp.datasource.infosys.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import de.hska.wi.awp.datasource.infosys.model.Statusbericht_geplante_arbeit;
import de.hska.wi.awp.datasource.infosys.service.Statusbericht_geplante_arbeitLocalServiceUtil;

/**
 * The extended model base implementation for the Statusbericht_geplante_arbeit service. Represents a row in the &quot;datasourceInfosys_Statusbericht_geplante_arbeit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Statusbericht_geplante_arbeitImpl}.
 * </p>
 *
 * @author Daniel Storch
 * @see Statusbericht_geplante_arbeitImpl
 * @see de.hska.wi.awp.datasource.infosys.model.Statusbericht_geplante_arbeit
 * @generated
 */
public abstract class Statusbericht_geplante_arbeitBaseImpl
    extends Statusbericht_geplante_arbeitModelImpl
    implements Statusbericht_geplante_arbeit {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a statusbericht_geplante_arbeit model instance should use the {@link Statusbericht_geplante_arbeit} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            Statusbericht_geplante_arbeitLocalServiceUtil.addStatusbericht_geplante_arbeit(this);
        } else {
            Statusbericht_geplante_arbeitLocalServiceUtil.updateStatusbericht_geplante_arbeit(this);
        }
    }
}
