package de.hska.wi.awp.datasource.infosys.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import de.hska.wi.awp.datasource.infosys.model.Teilnote_feedback;
import de.hska.wi.awp.datasource.infosys.service.Teilnote_feedbackLocalServiceUtil;

/**
 * The extended model base implementation for the Teilnote_feedback service. Represents a row in the &quot;datasourceInfosys_Teilnote_feedback&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Teilnote_feedbackImpl}.
 * </p>
 *
 * @author Daniel Storch
 * @see Teilnote_feedbackImpl
 * @see de.hska.wi.awp.datasource.infosys.model.Teilnote_feedback
 * @generated
 */
public abstract class Teilnote_feedbackBaseImpl
    extends Teilnote_feedbackModelImpl implements Teilnote_feedback {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a teilnote_feedback model instance should use the {@link Teilnote_feedback} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            Teilnote_feedbackLocalServiceUtil.addTeilnote_feedback(this);
        } else {
            Teilnote_feedbackLocalServiceUtil.updateTeilnote_feedback(this);
        }
    }
}
