package de.hska.wi.awp.datasource.infosys.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import de.hska.wi.awp.datasource.infosys.model.Teilnote;
import de.hska.wi.awp.datasource.infosys.service.TeilnoteLocalServiceUtil;

/**
 * The extended model base implementation for the Teilnote service. Represents a row in the &quot;datasourceInfosys_Teilnote&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TeilnoteImpl}.
 * </p>
 *
 * @author Daniel Storch
 * @see TeilnoteImpl
 * @see de.hska.wi.awp.datasource.infosys.model.Teilnote
 * @generated
 */
public abstract class TeilnoteBaseImpl extends TeilnoteModelImpl
    implements Teilnote {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a teilnote model instance should use the {@link Teilnote} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            TeilnoteLocalServiceUtil.addTeilnote(this);
        } else {
            TeilnoteLocalServiceUtil.updateTeilnote(this);
        }
    }
}
