package de.hska.wi.awp.datasource.infosys.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import de.hska.wi.awp.datasource.infosys.model.Teilnote_feedback;
import de.hska.wi.awp.datasource.infosys.model.Teilnote_feedbackModel;
import de.hska.wi.awp.datasource.infosys.model.Teilnote_feedbackSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Teilnote_feedback service. Represents a row in the &quot;datasourceInfosys_Teilnote_feedback&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link de.hska.wi.awp.datasource.infosys.model.Teilnote_feedbackModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Teilnote_feedbackImpl}.
 * </p>
 *
 * @author Daniel Storch
 * @see Teilnote_feedbackImpl
 * @see de.hska.wi.awp.datasource.infosys.model.Teilnote_feedback
 * @see de.hska.wi.awp.datasource.infosys.model.Teilnote_feedbackModel
 * @generated
 */
@JSON(strict = true)
public class Teilnote_feedbackModelImpl extends BaseModelImpl<Teilnote_feedback>
    implements Teilnote_feedbackModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a teilnote_feedback model instance should use the {@link de.hska.wi.awp.datasource.infosys.model.Teilnote_feedback} interface instead.
     */
    public static final String TABLE_NAME = "datasourceInfosys_Teilnote_feedback";
    public static final Object[][] TABLE_COLUMNS = {
            { "id_", Types.BIGINT },
            { "feedback_id", Types.BIGINT },
            { "note", Types.INTEGER },
            { "bewertungskriterium_id", Types.BIGINT }
        };
    public static final String TABLE_SQL_CREATE = "create table datasourceInfosys_Teilnote_feedback (id_ LONG not null primary key,feedback_id LONG,note INTEGER,bewertungskriterium_id LONG)";
    public static final String TABLE_SQL_DROP = "drop table datasourceInfosys_Teilnote_feedback";
    public static final String ORDER_BY_JPQL = " ORDER BY teilnote_feedback.id ASC";
    public static final String ORDER_BY_SQL = " ORDER BY datasourceInfosys_Teilnote_feedback.id_ ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.de.hska.wi.awp.datasource.infosys.model.Teilnote_feedback"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.de.hska.wi.awp.datasource.infosys.model.Teilnote_feedback"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.de.hska.wi.awp.datasource.infosys.model.Teilnote_feedback"),
            true);
    public static long BEWERTUNGSKRITERIUM_ID_COLUMN_BITMASK = 1L;
    public static long FEEDBACK_ID_COLUMN_BITMASK = 2L;
    public static long ID_COLUMN_BITMASK = 4L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.de.hska.wi.awp.datasource.infosys.model.Teilnote_feedback"));
    private static ClassLoader _classLoader = Teilnote_feedback.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Teilnote_feedback.class
        };
    private long _id;
    private long _feedback_id;
    private long _originalFeedback_id;
    private boolean _setOriginalFeedback_id;
    private int _note;
    private long _bewertungskriterium_id;
    private long _originalBewertungskriterium_id;
    private boolean _setOriginalBewertungskriterium_id;
    private long _columnBitmask;
    private Teilnote_feedback _escapedModel;

    public Teilnote_feedbackModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Teilnote_feedback toModel(Teilnote_feedbackSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Teilnote_feedback model = new Teilnote_feedbackImpl();

        model.setId(soapModel.getId());
        model.setFeedback_id(soapModel.getFeedback_id());
        model.setNote(soapModel.getNote());
        model.setBewertungskriterium_id(soapModel.getBewertungskriterium_id());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Teilnote_feedback> toModels(
        Teilnote_feedbackSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Teilnote_feedback> models = new ArrayList<Teilnote_feedback>(soapModels.length);

        for (Teilnote_feedbackSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _id;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _id;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Teilnote_feedback.class;
    }

    @Override
    public String getModelClassName() {
        return Teilnote_feedback.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("id", getId());
        attributes.put("feedback_id", getFeedback_id());
        attributes.put("note", getNote());
        attributes.put("bewertungskriterium_id", getBewertungskriterium_id());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long id = (Long) attributes.get("id");

        if (id != null) {
            setId(id);
        }

        Long feedback_id = (Long) attributes.get("feedback_id");

        if (feedback_id != null) {
            setFeedback_id(feedback_id);
        }

        Integer note = (Integer) attributes.get("note");

        if (note != null) {
            setNote(note);
        }

        Long bewertungskriterium_id = (Long) attributes.get(
                "bewertungskriterium_id");

        if (bewertungskriterium_id != null) {
            setBewertungskriterium_id(bewertungskriterium_id);
        }
    }

    @JSON
    @Override
    public long getId() {
        return _id;
    }

    @Override
    public void setId(long id) {
        _id = id;
    }

    @JSON
    @Override
    public long getFeedback_id() {
        return _feedback_id;
    }

    @Override
    public void setFeedback_id(long feedback_id) {
        _columnBitmask |= FEEDBACK_ID_COLUMN_BITMASK;

        if (!_setOriginalFeedback_id) {
            _setOriginalFeedback_id = true;

            _originalFeedback_id = _feedback_id;
        }

        _feedback_id = feedback_id;
    }

    public long getOriginalFeedback_id() {
        return _originalFeedback_id;
    }

    @JSON
    @Override
    public int getNote() {
        return _note;
    }

    @Override
    public void setNote(int note) {
        _note = note;
    }

    @JSON
    @Override
    public long getBewertungskriterium_id() {
        return _bewertungskriterium_id;
    }

    @Override
    public void setBewertungskriterium_id(long bewertungskriterium_id) {
        _columnBitmask |= BEWERTUNGSKRITERIUM_ID_COLUMN_BITMASK;

        if (!_setOriginalBewertungskriterium_id) {
            _setOriginalBewertungskriterium_id = true;

            _originalBewertungskriterium_id = _bewertungskriterium_id;
        }

        _bewertungskriterium_id = bewertungskriterium_id;
    }

    public long getOriginalBewertungskriterium_id() {
        return _originalBewertungskriterium_id;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            Teilnote_feedback.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Teilnote_feedback toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Teilnote_feedback) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        Teilnote_feedbackImpl teilnote_feedbackImpl = new Teilnote_feedbackImpl();

        teilnote_feedbackImpl.setId(getId());
        teilnote_feedbackImpl.setFeedback_id(getFeedback_id());
        teilnote_feedbackImpl.setNote(getNote());
        teilnote_feedbackImpl.setBewertungskriterium_id(getBewertungskriterium_id());

        teilnote_feedbackImpl.resetOriginalValues();

        return teilnote_feedbackImpl;
    }

    @Override
    public int compareTo(Teilnote_feedback teilnote_feedback) {
        long primaryKey = teilnote_feedback.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Teilnote_feedback)) {
            return false;
        }

        Teilnote_feedback teilnote_feedback = (Teilnote_feedback) obj;

        long primaryKey = teilnote_feedback.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        Teilnote_feedbackModelImpl teilnote_feedbackModelImpl = this;

        teilnote_feedbackModelImpl._originalFeedback_id = teilnote_feedbackModelImpl._feedback_id;

        teilnote_feedbackModelImpl._setOriginalFeedback_id = false;

        teilnote_feedbackModelImpl._originalBewertungskriterium_id = teilnote_feedbackModelImpl._bewertungskriterium_id;

        teilnote_feedbackModelImpl._setOriginalBewertungskriterium_id = false;

        teilnote_feedbackModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Teilnote_feedback> toCacheModel() {
        Teilnote_feedbackCacheModel teilnote_feedbackCacheModel = new Teilnote_feedbackCacheModel();

        teilnote_feedbackCacheModel.id = getId();

        teilnote_feedbackCacheModel.feedback_id = getFeedback_id();

        teilnote_feedbackCacheModel.note = getNote();

        teilnote_feedbackCacheModel.bewertungskriterium_id = getBewertungskriterium_id();

        return teilnote_feedbackCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(9);

        sb.append("{id=");
        sb.append(getId());
        sb.append(", feedback_id=");
        sb.append(getFeedback_id());
        sb.append(", note=");
        sb.append(getNote());
        sb.append(", bewertungskriterium_id=");
        sb.append(getBewertungskriterium_id());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(16);

        sb.append("<model><model-name>");
        sb.append("de.hska.wi.awp.datasource.infosys.model.Teilnote_feedback");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>id</column-name><column-value><![CDATA[");
        sb.append(getId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>feedback_id</column-name><column-value><![CDATA[");
        sb.append(getFeedback_id());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>note</column-name><column-value><![CDATA[");
        sb.append(getNote());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>bewertungskriterium_id</column-name><column-value><![CDATA[");
        sb.append(getBewertungskriterium_id());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
